services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: cirvee_postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cirvee
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cirvee-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cirvee"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: cirvee_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cirvee-network

  #  App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cirvee_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/cirvee?schema=public
      REDIS_HOST: redis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - cirvee-network
    command: npm run dev

  # Prisma Studio Service
  studio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cirvee_studio
    restart: unless-stopped
    ports:
      - "5555:5555"
    volumes:
      - .:/app               
      - /app/node_modules    
    env_file:
      - .env
    environment:
      BROWSER: none
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/cirvee?schema=public
    depends_on:
      app:
        condition: service_started
      postgres:
        condition: service_healthy
    networks:
      - cirvee-network
    command: npx prisma studio --browser none --port 5555

volumes:
  postgres_data:
  redis_data:

networks:
  cirvee-network:
    driver: bridge

    